### ISSUE TITLE
uri-js missing as dependency

### ISSUE THREAD

**Issue by walterjj** [namib-project/node-red-contrib-wot-discovery#80]
After a fresh installation of Node-RED 2.2.2 and node-red-contrib-wot-discovery,  a flow containing the wot-discovery node failed with a "wot-discovery type missing" ..
I fixed that installing uri-js by hand.

**Comment by JKRhb** [comment]
Thank you for reporting this issue! Do you want to open a PR with your fix?

**Comment by JKRhb** [comment]
Thanks again for opening this issue, @walterjj! As it turned out, uri-js was included as a dev-dependency, therefore I didn't notice that it was actually missing "in production". I currently making some more minor changes, then I will release a new version :)

**Comment by JKRhb** [comment]
A new version has now been released :) Let me know if you should encounter any more issues.

**Comment by walterjj** [comment]
Good!  thank YOU for you such a good job with this project!
